services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80" # HTTP port for the web service
    develop:
      watch:
        - action: sync # Sync changes to source code into the container
          path: ./src
          target: /var/www/html
          ignore:
            - .git/
            - "*.tmp"
        - action: sync # Sync changes to the uploads directory
          path: ./uploads
          target: /var/www/uploads
          ignore:
            - .git/
            - "*.tmp"
        - action: rebuild # Rebuild the service if Dockerfile changes
          path: ./docker/Dockerfile
        - action: rebuild # Rebuild the service if dependencies change
          path: ./docker-compose.yaml
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel_advisory
    ports:
      - "3306:3306" # MySQL port for database access
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
