version: "3" # Specify a supported version of Docker Compose
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80" # HTTP port for the web service
    volumes:
      - ./src:/var/www/html
      - ./uploads:/var/www/uploads
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel_advisory
    ports:
      - "3306:3306" # MySQL port for database access
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: # This is now defined correctly
